kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mule-build" 
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "GitHub"
      github:
        secret: "secret101"
    - type: "Generic"
      generic:
        secret: "secret101"
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/dkudale/mule-docker.git"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "mule-esb-3.9.0:latest"